# Generated by Django 4.2.13 on 2025-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_student_studentprogress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='video_progress',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('user', 'course')},
        ),
    ]
